[workspace]
resolver = "2"
members = [
    "crates/lumenplot",
    "crates/lumenplot-engine",
    "crates/lumenplot-export",
    "crates/lumenplot-render-api",
    "crates/lumenplot-render-wgpu",
    "crates/lumenplot-runtime",
    "crates/lumenplot-viewer",
    "crates/lumenplot-python",
    "crates/lumenplot-bench",
]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/SoichiroYamane/lumenplot"
readme = "README.md"
