[package]
name = "lumenplot-export"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
lumenplot-engine = { path = "../lumenplot-engine", version = "0.1.0" }
tiny-skia = { version = "=0.12.0", default-features = false, features = ["std"] }
png = { version = "=0.18.1", default-features = false }
