[package]
name = "lumenplot-viewer"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
lumenplot = { path = "../lumenplot", version = "0.1.0" }
lumenplot-runtime = { path = "../lumenplot-runtime", version = "0.1.0" }
